### ISSUE TITLE
hey..

### ISSUE THREAD

**Issue by halt-spesn** [smithhun10/device_xiaomi_spes#1]
i noticed you already did it.. my matrix tag is @shifty.rc:matrix.org if you don't planning to come back in tg

**Comment by smithhun10** [comment]
> i noticed you already did it.. my matrix tag is @shifty.rc:matrix.org if you don't planning to come back in tg

how do I use this 'matrix' site? can u share new tg account details so I can get back on tg

**Comment by halt-spesn** [comment]
> > i noticed you already did it.. my matrix tag is @shifty.rc:matrix.org if you don't planning to come back in tg
> 
> how do I use this 'matrix' site? can u share new tg account details so I can get back on tg
nubmer for tg account i created is +447389661060

**Comment by smithhun10** [comment]
> > > i noticed you already did it.. my matrix tag is @shifty.rc:matrix.org if you don't planning to come back in tg
> > 
> > 
> > how do I use this 'matrix' site? can u share new tg account details so I can get back on tg
> > nubmer for tg account i created is +447389661060

please email me
